### ISSUE TITLE
xfs filesystem supports timestamps until 2038

### ISSUE THREAD

**Issue by leoluk** [monogon-dev/monogon#1]
(originally reported by @q3k in T967)

bazel run //:launch:

    [   17.338739] xfs filesystem being mounted at /data supports timestamps until 2038 (0x7fffffff)

We could pass `-m bigtime=1` to mkfs.xfs, but then the log says:

    [   51.272631] XFS (dm-1): EXPERIMENTAL big timestamp feature in use. Use at your own risk!

Not sure which is better :).

**Comment by q3k** [comment]
I think at some point we decided to not actually act on this for now - as we expect that once 'big timestamps' are non-experimental in XFS, we'll just turn that on; and in the meantime, we'll live with the year 2038 warning.

Tentatively moving this out of Cluster MVP. @leoluk, that alright?

**Comment by leoluk** [comment]
Sgtm

**Comment by lorenz** [comment]
We just need to bump xfsprogs to 5.15 or later which we should do anyways and that will automatically enable bigtime. Minimum kernel version is 5.10 which is much older than what we're shipping already.
