### ISSUE TITLE
Enable FB/GOP in Linux

### ISSUE THREAD

**Issue by q3k** [monogon-dev/monogon#103]
`third_party/linux/linux-metropolis.config` says:

```
#
# Frame buffer Devices
#
# CONFIG_FB is not set
# end of Frame buffer Devices
```

We should definitely enable framebuffer support and efifb/EFI GOP. We don't want to just depend on serial output.

**Comment by lorenz** [comment]
https://review.monogon.dev/c/monogon/+/517
