### ISSUE TITLE
Curator/Curator API: missing API surface for cluster management

### ISSUE THREAD

**Issue by q3k** [monogon-dev/monogon#104]
We should do a pass to ensure a basic set of APIs are available to manage nodes within a cluster, and the cluster itself - things that we already might have logic for, but don't have the right knobs exposed via gRPC.

Relevant service:

https://github.com/monogon-dev/monogon/blob/main/metropolis/proto/api/management.proto

**Comment by msgctl** [comment]
Ideas for features to implement:
- reporting node status (heartbeat-like)
- changing node roles (probably non-MVP)
- draining/decommissioning of nodes
- node configuration
- CA introspection (inspecting certificates, certificate revocation, current CRL)
- inspecting the current Curator leader (status, node list, quorum)
- identity management (users?)

**Comment by q3k** [comment]
Sample user stories for some of the above (these are not just APIs to implement, but probably also metroctl flows):

1. As an Operator, I want to know what is the state of nodes in my cluster: are they UP? are there any non-UP nodes? when was the last time they reported to the cluster/curator?
2. As an Operator, I want to inspect and even change the assigned roles to nodes. How many Control Plane nodes do we have?
3. As an Operator, I want to know what's the status of my control plane nodes. Which node is the Curator leader? What are the followers? When did the leadership begin? When will it timeout?

**Comment by q3k** [comment]
> 2. As an Operator, I want to inspect and **even change** the assigned roles to nodes. How many Control Plane nodes do we have?

I think we should only (at first) allow:
  1. adding a ConsensusMember role where there wasn't any
  2. adding a KubernetesWorker role where there wasn't any _and_ that node is already a ConsensusMember (this limit applies as long as we don't split KubernetesWorker into KubernetesControlPlane and KubernetesWorker)
  3. removing a KubernetesWorker roles where there wasn't any, but we'll have to also think about removing nodes from Kubernetes itself when that happens

Point 3. is a bit more involved because it requires interacting with Kubernetes, let's start with 1 and 2.

**Comment by msgctl** [comment]
↑ both should be landing this week.

**Comment by msgctl** [comment]
https://review.monogon.dev/c/monogon/+/775 implements role-based filtering in Management.GetNodes RPC.
https://review.monogon.dev/c/monogon/+/776 enables predicates related to node heartbeats.

These conclude the user story no 1.

**Comment by q3k** [comment]
What's left to do here?

**Comment by msgctl** [comment]
Just the last user story, if we're going to limit this long standing ticket to the ones you posted (which I think we should, due to lack of other present use cases):
>3. As an Operator, I want to know what's the status of my control plane nodes. Which node is the Curator leader? What are the followers? When did the leadership begin? When will it timeout?
One can get the current leader node's ID through a call to CuratorLocal.GetCurrentLeader. The follower list can be accessed with an appropriate filter supplied to Management.GetNodes, though it's true it could be made more accessible than that. I'll be adding the leadership timestamp and TTL to GetCurrentLeader results.
