### ISSUE TITLE
Node Join Flow: Join Credentials

### ISSUE THREAD

**Issue by q3k** [monogon-dev/monogon#105]
Part of #99.

As defined in the Cluster Lifecycle DD, we don't want anyone to be able to contact a cluster claiming that they are a node that wishes to join it (after rebooting).

The target flow is the following:
 1. During Bootstrap/Registration, next to generating a Node keypair for Node credentials, a node should generate a Join keypair.
 2. The Node's Join Public Key should be submitted to the cluster as that node's Join PK.
 3. The Node's Join Keypair should be saved to the ESP, sealed using TPM.
 4. On Join, a Node will unseal its Join Keypair and use a saved Cluster Directory to contact its Cluster.
 5. The Node and Cluster will mutually hardware attest eachother.
 6. After mutual verification, the Cluster will give out the node's Cluster Unlock Key to the booting Node.
 7. The Node will use the CUK to mount its Data partition.

Since we're currently skipping step 7 (hardware attestation) the Join keypair is effectively as powerful as the Node credentials/keypair. However, with the introduction of HA, this will not be the case anymore, and the Join keypair will instead act as a set of “Courtyard” credentials to be able to start performing HA (itself an expensive operation).

All the above steps of the flow need to be implemented.

**Comment by msgctl** [comment]
Current WIP patch: https://review.monogon.dev/c/monogon/+/556

Still working on e2e tests.

**Comment by lorenz** [comment]
Merged as part of #99
