### ISSUE TITLE
Update build container

### ISSUE THREAD

**Issue by q3k** [monogon-dev/monogon#111]
Our build container uses Fedora 32, which is EOL.

Updating to Fedora 36 causes some issues with GCC 11: https://review.monogon.dev/c/monogon/+/529/3

We should either figure these out, or bump to a slightly older Fedora with GCC 10, or move to LLVM (I think we attempted this before?) or finally figure out containerless builds (via proper Bazel toolchains).

**Comment by leoluk** [comment]
Oh well, `:launch` works but the tests break:

<img width="869" alt="image" src="https://user-images.githubusercontent.com/859697/155142538-8d225fc9-a8de-4fd1-b203-57961a85481e.png">

**Comment by leoluk** [comment]
Apparently Bazel doesn't like it when the ambient environment changes. `bazel clean --expunge` fixes the error above.

**Comment by leoluk** [comment]
*Sigh* looks like we need it after all, Fedora 34 doesn't work either.

**Comment by lorenz** [comment]
Updated to Fedora 35 in https://review.monogon.dev/c/monogon/+/529
