### ISSUE TITLE
Curator Leader Failover

### ISSUE THREAD

**Issue by q3k** [monogon-dev/monogon#112]
Currently, the Curator cannot function in follower mode, and the roleserver only dials the first node of the cluster (ie. the curator that should be the leader, until failover).

We should implement this and exercise this in some end-to-end test.

**Comment by q3k** [comment]
Currently implementing cluster-wide 'dynamic' client, which is needed to contact multiple nodes' curators and thus be able to fail over between them in case of issues.

**Comment by q3k** [comment]
Dynamic client tracking issue: https://github.com/monogon-dev/monogon/issues/117

**Comment by lorenz** [comment]
Work is being done on making the client only dial the current curator leader as proxying turned out to be painful due to mTLS.

**Comment by q3k** [comment]
Progress: this is generally working, but getting it to a 100% exposes some bugs and small issues with assumptions. Still on the right track to ship this soon.

**Comment by lorenz** [comment]
This should now work as 796 has been landed, but it has no tests yet. Bumping from MVP and waiting for tests to be implemented.
