### ISSUE TITLE
Dynamic Cluster Client

### ISSUE THREAD

**Issue by q3k** [monogon-dev/monogon#117]
We currently only have the following method in the rpc package:

```
func NewAuthenticatedClient(remote string, cert tls.Certificate, ca *x509.Certificate, opts ...grpc.DialOption) (*grpc.ClientConn, error) {
```

Which needs a concrete Curator/node address, and will not load-balance or fail over between Curators.

We need such a client both internally (to load-balance and fail over to the right curator) and externally (to connect to a cluster given just a ClusterDirectory or even the address of a single 'bootstrap' node).

**Comment by q3k** [comment]
First implementation: https://review.monogon.dev/c/monogon/+/637

**Comment by lorenz** [comment]
Landed as part of CL 637
