### ISSUE TITLE
Handling core process crashes

### ISSUE THREAD

**Issue by lorenz** [monogon-dev/monogon#121]
* Restarting
* Collect crash data and store it
  * On disk if reliably possible
  * In pstore
* Empty pstore on node boot

**Comment by lorenz** [comment]
https://review.monogon.dev/c/monogon/+/772 implements this

**Comment by q3k** [comment]
We also need to capture panics() in tests launched with //metropolis/test/launch/cluster, eg. e2e tests.

Currently they go to stderr, which is not /dev/tty(S)0 or another console piped to the user.

**Comment by lorenz** [comment]
Leaving testing for #130
