### ISSUE TITLE
Protos: consider moving from int64 nanosec timestamps to google.protobuf.Timestamp

### ISSUE THREAD

**Issue by q3k** [monogon-dev/monogon#129]
The advantages of google.protobuf.Timestamp are:

 - nicer canonical represesentation in JSON mapping (RFC3399 string vs. raw number)
 - longer time period coverered (year 0-9999 vs 1970 to 2xxx)

**Comment by msgctl** [comment]
https://review.monogon.dev/c/monogon/+/831
https://review.monogon.dev/c/monogon/+/832
