### ISSUE TITLE
Tracking Issue: Deployment Agent

### ISSUE THREAD

**Issue by q3k** [monogon-dev/monogon#146]

**Comment by q3k** [comment]
Last week progress has been made on the deployment agent proto definition by @lorenz .

Now investigating the best way to ship operating systems. Likely going with original 'upstream' distribution images and integrating over cloud-init via “No Cloud” metadata over a separate partition.This would be created by the deployment agent, integrating discovered data from the initial OS and user-provided metadata.

With cloud-init we still have to decide which network configuration schema version we should be using. v2/netplan is the most attractive due to its capabilities, but we need to check which of our supported OS images actually are able to consume it.

To generate the cloud-init/netplan config we can either fully construct that ourselves (by autodiscovering on the host) or “steal” parts of it from the provider OS configuration.

**Comment by lorenz** [comment]
Prototype for this is getting close, currently implementing reading support for the GPT library to be able to place NoCloud partitions. Prototype is still a bit rough, needs testing and un-hardcoding stuff. But a bunch of things have already been validated on it.

**Comment by msgctl** [comment]
GPT library PR: https://review.monogon.dev/c/monogon/+/956

**Comment by q3k** [comment]
Split this into smaller issues, see milestone.
