### ISSUE TITLE
Deployment: Equinix Shepherd

### ISSUE THREAD

**Issue by q3k** [monogon-dev/monogon#148]

**Comment by q3k** [comment]
Current provider status:

 - Equinix: existing Go library (packngo)
 - Zenlayer: OpenAPI spec, succesfully generated stubs using https://github.com/OpenAPITools/openapi-generator
 - Lumen: Probably based on Morpheus, we should try https://github.com/gomorpheus/morpheus-go-sdk

**Comment by q3k** [comment]
Shifted focus to Equinix and Stackpath.

Thanks to @msgctl, we now have a preliminary Stackpath client and Shepherds (ie. integration agents) coming up for both Stackpath and Equinix. Things should start getting out for review this week.

**Comment by msgctl** [comment]
No updates yet. I'm still getting my implementation ready for submission.

**Comment by msgctl** [comment]
Currently rebasing on top of the newly arrived BMDB implementation: https://review.monogon.dev/c/monogon/+/953

**Comment by msgctl** [comment]
We're iterating these related CRs:
https://review.monogon.dev/c/monogon/+/998
https://review.monogon.dev/c/monogon/+/989
https://review.monogon.dev/c/monogon/+/990

**Comment by msgctl** [comment]
See CRs for updates on the progress.

**Comment by q3k** [comment]
Equinix wrapper in progress.

**Comment by lorenz** [comment]
Still refactoring.

**Comment by q3k** [comment]
Currently working on adapting @msgctl's changes to fit better with the BMDB API, as I was the one to birth it.

wrapngo is done, I also mode it context-aware-ish, that'll be reviewable soon.

The Shepherd Manager change is in progress.

**Comment by q3k** [comment]
Sent out new Shepherd changes but our Gerrit is currently down. I'll update this issue whenever it comes back up...

**Comment by q3k** [comment]
Done: https://review.monogon.dev/c/monogon/+/1129
