### ISSUE TITLE
Use standard Bazel cache directory

### ISSUE THREAD

**Issue by leoluk** [monogon-dev/monogon#150]
We should consider using the standard Bazel cache directory vs. our own.

Right now, IntelliJ users have to specify `-Dbazel.bep.path=/home/leopold/.cache/bazel-monogon`, which breaks all other projects.

**Comment by lorenz** [comment]
So this can done in two ways:
1. Get rid of the build container. We probably want to do this anyways.
2. Move IntelliJ into the container.

Sharing a cache between multiple namespaces is likely to go poorly.

**Comment by leoluk** [comment]
(we agreed that this is fraught with peril and time is better spent getting rid of the container)
