### ISSUE TITLE
Deployment: Mini-Shepherd

### ISSUE THREAD

**Issue by q3k** [monogon-dev/monogon#152]
Implement a set of control loops to interface between the BMDB and the API defined in https://github.com/monogon-dev/monogon/issues/151.

This will be a 'generic' shepherd implementation mostly for users with bespoke machine provisioning mechanism. We'll use this architecture for interfacing with the Lumen panel via the aforementioned proxy.

**Comment by q3k** [comment]
First DD related to this is splitting up the existing Shepherd into something where we can easily build different provider backends.

https://docs.google.com/document/d/1mJ_Cra-WIHuFmatRdb7U24uZ-uR_z4_oTNoU7_dSjmE/edit#heading=h.wwgnimruvhlu

Next step will be to implement a generic 'mini-shepherd' as per this issue that works on local lists of files.

**Comment by lorenz** [comment]
Implemented now, waiting for submission dependencies

**Comment by fionera** [comment]
Submitted. Replacing custom image with main branch nightly now

**Comment by fionera** [comment]
Still running a handcrafted image but thats based on `main`. Currently working on getting the build working but that's tracked in #265
