### ISSUE TITLE
BMDB: Finalize tags for BMaaS

### ISSUE THREAD

**Issue by q3k** [monogon-dev/monogon#153]
We need a finalized spec and implementation of initial BMDB tags / schema.

**Comment by q3k** [comment]
Still missing right now:

1. Agent HW report
2. OS installation request
3. OS installation report
4. User visibility
5. Failures/backoff
6. Network information?

**Comment by q3k** [comment]
1, 2 and 3 are done/pending review. I'll work on failures/backoff next.

**Comment by lorenz** [comment]
Progress on backoff/failures, also doing history/audit table. 2 and 3 still stuck in review.

**Comment by q3k** [comment]
2 and 3 got merged. I am stil working on failures/backoff (got pre-empted by other things this week).

**Comment by q3k** [comment]
Everything apart from user visibility and networking is done. Closing this and filing issues for just these two.
