### ISSUE TITLE
E2E test can reboot node before cluster directory is initialized

### ISSUE THREAD

**Issue by leoluk** [monogon-dev/monogon#170]
This is currently unrecoverable:

https://gist.githubusercontent.com/leoluk/b96f57c43648fc71d5114706abc383ca/raw/01e224a8834367a9b36fba665e42e6bd733bdaa4/gistfile1.txt

**Comment by q3k** [comment]
Fixed in https://github.com/monogon-dev/monogon/commit/630fb5c5349b13330b7de6f8300b495b801db061

E2E test is now significantly less flake'y, but not fully deflaked.
