### ISSUE TITLE
Add additional sandbox hermeticity flags

### ISSUE THREAD

**Issue by leoluk** [monogon-dev/monogon#176]
Now that we rely on the linux-sandbox spawn strategy, we can flip on a few more flags that should improve reproducibility:

- [`--incompatible_sandbox_hermetic_tmp`](https://bazel.build/reference/command-line-reference#flag--incompatible_sandbox_hermetic_tmp) (not entirely sure what is happening right now... do we end up with files inside the sandboxroot /tmp, or the host's? 🤔)
- [`--reuse_sandbox_directories`](https://bazel.build/reference/command-line-reference#flag--reuse_sandbox_directories). Free performance improvement, see also https://github.com/bazelbuild/bazel/issues/16138.
- [`--sandbox_fake_hostname`](https://bazel.build/reference/command-line-reference#flag--sandbox_fake_hostname)
- [`--sandbox_fake_username`](https://bazel.build/reference/command-line-reference#flag--sandbox_fake_username)

More flags to consider: https://docs.aspect.build/guides/bazelrc/

**Comment by lorenz** [comment]
Submitted in https://review.monogon.dev/c/monogon/+/2700
