### ISSUE TITLE
Run :launch without sandbox

### ISSUE THREAD

**Issue by leoluk** [monogon-dev/monogon#181]
Now that the container is gone, we can't run :launch with "bazel run" anymore since this is now running directly on the host, which has neither QEMU nor swtpm. As a workaround, we cheat by running it as a test (e2a302a9062d3ebfc33ad83dd382653e067ca009), but that takes the Bazel lock and times out after a bit.

Instead, we need to build static QEMU and swtpm binaries that can run on the host independently:

- https://github.com/monogon-dev/monogon/issues/180
- https://github.com/monogon-dev/monogon/issues/81

Installing qemu and swtpm on corp workstations works, but it's not ideal.

**Comment by q3k** [comment]
There is another problem with running these as tests: Crl-C/SIGINT does not get passed through to the code (and I think instead it just gets killed?). Currently this means we end up with a whole bunch of junk in /tmp that would've usually been cleaned up by cleanup routines.

**Comment by fionera** [comment]
Since we run inside a nix-shell we could make it a requirement, right?

**Comment by q3k** [comment]
Fixed in https://review.monogon.dev/c/monogon/+/3105 / d02c6c7745943f19d453f6fba0bfb701e7f222df.
