### ISSUE TITLE
Deploy new Dockerfile in CI

### ISSUE THREAD

**Issue by leoluk** [monogon-dev/monogon#182]
Redeploy CI with new Dockerfile: https://github.com/monogon-dev/monogon/blob/main/build/ci/Dockerfile

Remove this:

https://github.com/monogon-dev/monogon/blob/d6397766915e4427f74d59656718acffc92d872c/build/ci/jenkins-presubmit.groovy#L5-L6

**Comment by fionera** [comment]
Already done
