### ISSUE TITLE
webug: show provider status 

### ISSUE THREAD

**Issue by fionera** [monogon-dev/monogon#201]
Equinix has Running, Stopped and Failed as status. We should make that visible in webug

**Comment by q3k** [comment]
We currently don't have this data in BMDB. Does this mean you want to add an extra tag to the BMDB that reflects the state as seen as the provider?

**Comment by q3k** [comment]
We now have this in the BMDB in the Provider field (/cdb325ee1cd0b3f3e6db46d8d933d0ab519a5d14). Is this enough, or do you want to also be shown in a list view?

**Comment by fionera** [comment]
I think we want this in the list view. Maybe as color for the machine id? (Red = failed, gray = off, green = running)?
