### ISSUE TITLE
webug: show location

### ISSUE THREAD

**Issue by fionera** [monogon-dev/monogon#202]

**Comment by q3k** [comment]
We don't have this data in BMDB. This means we should either add this to the Provided tag, or introduce a separate tag.

**Comment by q3k** [comment]
We now have this in the BMDB in the Provider field (/cdb325ee1cd0b3f3e6db46d8d933d0ab519a5d14). Is this enough, or do you want to also be shown in a list view?

**Comment by fionera** [comment]
Yeah I think that would be a nice addition to the Provided tag string. Maybe remove the uuid itself and make Equinix clickable?
