### ISSUE TITLE
shepherd: allow adding additional ssh key 

### ISSUE THREAD

**Issue by fionera** [monogon-dev/monogon#209]
to debug we also want a secondary ssh key added to all machines

**Comment by fionera** [comment]
No. We override it in the deployment api call

**Comment by fionera** [comment]
I added a flag to not add any key which will use the default behavior of adding all keys

**Comment by fionera** [comment]
The flag doesnt get accepted smh. This needs some debugging. For now I hardcoded it in the prod container

**Comment by fionera** [comment]
```
$ bazelisk run cloud/shepherd/equinix/manager/server:server -- -shepherd_prometheus_insecure "true" -provisioner_use_project_keys "true"
provisioner_use_project_keys: false

$ bazelisk run cloud/shepherd/equinix/manager/server:server -- -shepherd_prometheus_insecure -provisioner_use_project_keys "true"
provisioner_use_project_keys: true
```
o.O

**Comment by q3k** [comment]
Go flags are odd: `-foo false` sets `foo` to true (by enabling it when specified) and puts false into `flag.Args`.

https://pkg.go.dev/flag#hdr-Command_line_flag_syntax

This is indeed a footgun and I'm surprised I/we haven't hit that earlier.

**Comment by fionera** [comment]
https://review.monogon.dev/c/monogon/+/1798 introduces a check for NArgs
