### ISSUE TITLE
cloud: No Network on machines

### ISSUE THREAD

**Issue by fionera** [monogon-dev/monogon#224]
We are still facing the issue that machine scant boot. Currently the issue stands with having the ice base boxes to be configured correctly. @lorenz mentioned that the driver takes longer to initialize than our networking, which causes a race. There is a workaround in https://review.monogon.dev/c/monogon/+/1808 by just restarting network.

**Comment by fionera** [comment]
The fix works for now: https://bin.monogon.dev/pasta/spider-shark-bee

**Comment by lorenz** [comment]
Fixed by https://review.monogon.dev/c/monogon/+/1808 which allows the network service to restart until the NICs are ready.
