### ISSUE TITLE
node: dont spam resolver failures on startup

### ISSUE THREAD

**Issue by fionera** [monogon-dev/monogon#227]
Currently the nodes spam the serial with failed leader requests

            resolver I WATCHLEADER: failed to retrieve current leader from -:7835: rpc error: code =
                     | Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp
                     | -:7835: connect: connection refused"

**Comment by lorenz** [comment]
Problem is actually that the cluster directory does not contain a marker for control plane nodes, meaning that it tries to connect to 100s of nodes which do not run a curator

**Comment by q3k** [comment]
Fixed in https://review.monogon.dev/c/monogon/+/1840 .
