### ISSUE TITLE
node: Adding KubernetesWorker to a node in New state blocks rollout of other nodes

### ISSUE THREAD

**Issue by fionera** [monogon-dev/monogon#234]
When setting up a new cluster you can currently add the KubernetesWorker role to a Node that is still in New state. That will prevent other nodes to join the k8s cluster. Approving these new Nodes will fix it.

Solution: block adding roles to nodes in new state.

**Comment by q3k** [comment]
I also tried swapping steps 2 and 3 and that also works.

**Comment by q3k** [comment]
@fionera Have you observed this behaviour during the newest cluster re-deployments?

**Comment by q3k** [comment]
Closing this as this wasn't able to be replicated and didn't happen in production again.
