### ISSUE TITLE
A/B Updates

### ISSUE THREAD

**Issue by q3k** [monogon-dev/monogon#239]
We want to be able to roll out nodes to a newer version of a Metropolis bundle.

**Comment by q3k** [comment]
WIP change: https://review.monogon.dev/c/monogon/+/1874

**Comment by lorenz** [comment]
Implemented in [35fcf03](https://github.com/monogon-dev/monogon/commit/35fcf0397be02883ace364e650b3e8d9a2281e24), kexec-based activation in https://review.monogon.dev/c/monogon/+/2021
