### ISSUE TITLE
//metropolis/node:image_gcp flake

### ISSUE THREAD

**Issue by leoluk** [monogon-dev/monogon#251]
Whatever this is: https://jenkins.monogon.dev/job/gerrit-presubmit-monogon/job/53%252F1953%252F1/1/console

<pre>
ERROR: /home/ci/monogon/metropolis/node/BUILD.bazel:169:8: Executing genrule //metropolis/node:image_gcp failed: (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
gzip: warning: GZIP environment variable is deprecated; use an alias or script
<b>tar: disk.raw: file changed as we read it</b>
</pre>

https://github.com/Distrotech/tar/blob/273975bec1ff7d591d7ab8a63c08a02a285ffad3/src/create.c#L1788-L1793

This isn't even a test. I don't really see how this could happen unless some concurrent rule modifies the output root, if such a thing is even possible (shouldn't inputs be mapped read-only?)

May or may not be related:

- https://github.com/bazelbuild/sandboxfs/issues/116

**Comment by lorenz** [comment]
https://jenkins.monogon.dev/job/gerrit-presubmit-monogon/job/74%252F1874%252F22/1/console

Just got the CI to reproduce it.

**Comment by lorenz** [comment]
This has now gotten to near-100% CI reproducibility, I can barely get a successful build anymore. I looked into it again and I still cannot see what causes this.
