### ISSUE TITLE
Full identity system

### ISSUE THREAD

**Issue by leoluk** [monogon-dev/monogon#26]
(originally reported by @q3k in T934)

Implement the identity part of our cluster lifecycle design doc, augmented with user stories from https://github.com/monogon-dev/internal/issues/2.

**Comment by leoluk** [comment]
For the HSM use case, we can fully delegate this to an external SSO mechanism (i.e. Azure OAuth).

**Comment by q3k** [comment]
Rolling this into #12 and making that the main identity tracking issue.
