### ISSUE TITLE
Bootentryless A/B boot: clean up old style EFI boot variables

### ISSUE THREAD

**Issue by q3k** [monogon-dev/monogon#279]
Since we migrated to 'bootentryless' boots (via a preloader), there are some nodes (AMD in Equinix) which still apparently use old boot entries and boot into old Metropolis versions.

Thankfully, we have kexec on these machines so we can still ship and update: one that would make sure we don't have any leftover old-style boot entries.

**Comment by q3k** [comment]
https://review.monogon.dev/c/monogon/+/2413

**Comment by lorenz** [comment]
Code has been deployed to Equinix and seems to work.
