### ISSUE TITLE
metropolis: Add labels to nodes

### ISSUE THREAD

**Issue by fionera** [monogon-dev/monogon#281]
We do want a way of adding labels to nodes. These should also be published to k8s.

**Comment by q3k** [comment]
First napkin math design:

1. Store node metadata somewhere in etcd
2. Allow mutating said metadata via Management RPCs
3. Allow prepopulating said metadata via Node startup parameters
4. Reconcile from node metadata to Kubernetes node annotations in the Curator (or let nodes update this data themselves?)

**Comment by lorenz** [comment]
We have node labels on the Metropolis side of things, but do not synchronize them into K8s yet.

**Comment by q3k** [comment]
Done ( https://review.monogon.dev/c/monogon/+/3470 and friends).
