### ISSUE TITLE
metropolis: replace coredns 

### ISSUE THREAD

**Issue by fionera** [monogon-dev/monogon#283]
CoreDNS is just a shit show and we should just move away from it. There is already an open CL which still needs some love

**Comment by fionera** [comment]
Docs https://github.com/kubernetes/dns/blob/master/docs/specification.md

**Comment by lorenz** [comment]
Done as of [53964c1](https://github.com/monogon-dev/monogon/commit/53964c1343dd37e29c8a61a44f47202b3f3726cc).
