### ISSUE TITLE
multi node cluster fails to reboot

### ISSUE THREAD

**Issue by fionera** [monogon-dev/monogon#292]
- When rebooting a cluster with three nodes where all of them are etcd members fails when rebooting all of them at the same time.

- When rebooting a cluster with two nodes where all of them are etcd member fails when rebooting one of them

**Comment by lorenz** [comment]
Logs (only internally accessible): https://bin.monogon.dev/upload/eel-ant-goose

**Comment by q3k** [comment]
This should have been fixed by now (eg. by fixing cluster directory serialization).
