### ISSUE TITLE
Write handbook for cluster MVP

### ISSUE THREAD

**Issue by leoluk** [monogon-dev/monogon#31]
(originally reported by @q3k in T849)

**Comment by q3k** [comment]
WIP change: https://review.monogon.dev/c/monogon/+/453

Not working on this actively, someone can pick this up, dust it off and merge what we have.

**Comment by q3k** [comment]
Updated the WIP change with a bit more prose (notably the Cluster Architecture overview/introduction).

One last self-edit pass and then it'll be out for review.

**Comment by q3k** [comment]
Editing pass in progress, received comments from reviewers, if the stars align we'll have this merged this week.

Next step is to get this pushed to a publicly served page, let's go with https://docs.monogon.dev/metropolis/ backed by a GCP bucket, directly pushed from a Jenkins CI job. We'll make this nicer (multiple versions, etc) as we go along.

**Comment by lorenz** [comment]
MVP handbook done, publishing pipeline done. Will go up automatically as soon as the release is tagged.
