### ISSUE TITLE
//metropolis/launch-cluster: allow specifying launch parameters on command line

### ISSUE THREAD

**Issue by q3k** [monogon-dev/monogon#315]
In addition to https://github.com/monogon-dev/monogon/issues/309 , it would be nice to be able to configure:

1. How much memory / CPU each node has
2. What preassigned roles should nodes get (separately for each node)
3. Initial cluster configuration, eg. TPM policy, disk encryption policy
4. If applicable, per-node NodeParameters like TPM mode and disk encryption mode (if we even allow configuring this, I don't remember)

**Comment by jscissr** [comment]
We need to decide on the command line syntax for specifying the nodes to which an option applies.

Proposal 1:
`launch-cluster -num-nodes=4 -cpu=4 -node=0 -cpu=2 -node=1-3 -ram=4G -kubernetes-worker`

Proposal 2:
 `launch-cluster -num-nodes=4 -cpu=4 -cpu=2@0 -ram=4G@1-3 -kubernetes-worker=1-3`

In both cases, arguments are processed from left to right. First, all nodes get 4 CPUs by default. Then, node 0 is set to 2 CPUs, and the remaining three nodes get 4GB of RAM and the Kubernetes Worker role.

We could also decide to not make CPU and RAM configurable per node:
 `launch-cluster -num-nodes=4 -cpu=4 -ram=4G -kubernetes-worker=1-3`
