### ISSUE TITLE
Fully convert monorepo to bzlmod

### ISSUE THREAD

**Issue by leoluk** [monogon-dev/monogon#343]
From what I understand about the design, this should allow us to depend on the monorepo from internal.git, while maintaining MVS semantics.

We should also set appropriate visibility rules to make sure we don't unintentionally expose APIs which we later regret.

**Comment by fionera** [comment]
This does add some workarounds for e.g. https://github.com/bazelbuild/bazel/issues/19301

**Comment by fionera** [comment]
And to completely remove WORKSPACE we need to wait for https://github.com/rmohr/bazeldnf/issues/60

**Comment by fionera** [comment]
> > This does add some workarounds for e.g. [bazelbuild/bazel#19301](https://github.com/bazelbuild/bazel/issues/19301)
> 
> 
> 
> Are we blocked on this?

No we aren't. It's just not pretty :)

**Comment by fionera** [comment]
Technically not correct but we will leave it closed as we are currently only waiting for bazeldnf
