### ISSUE TITLE
Improve working with long supervisor DNs

### ISSUE THREAD

**Issue by lorenz** [monogon-dev/monogon#71]
We already have a few supervisor DNs which are quite long. This recently came up while reviewing a CL adding another two hierarchy levels onto the k8s service which already has quite long DNs.

These ultra-long DNs are bad for UX as they are a pain to type to get logs from and make for extremely long log lines.

A few ideas courtesy of @q3k:

 1. Limit our runnable name lengths, or rearrange the supervision tree to make the DNs shorter.
 2. Introduce separate 'short' names for logging and other ops interactions.
 3. Make the client-side tooling handle these names better, ie. shorten them where possible and requested.

> I don't like 1. as it breaks abstractions: it influences the way we set up runnables because we end up with long DNs that are annoying to interact with when consuming logs. It artificially limits the usefulness of the supervisor because of something somewhat unrelated.
> I don't like 2. as it breaks the symmetry between the supervision tree and the logging DNs. I could be convinced to maybe set up an obviously separate namespace for short log paths (eg. rename root.* to sup[ervisor].*, and introduce a shorter named.* where runnable could alias themselves into when requested). But that's a large design change, and there's a bunch of corner casese to consider.
> 3. seems to me the least impedance-mismsatched and fastest to implement - there's a couple of low hanging fruits we could easily implement, like some name shortening scheme for output stdout logs (eg. rroot.roleserver.kubernetes-worker.run.controller-manager becomes r.r.kw.r.controller-manager), tab completion in the dbg client, ... And if that doesn't work, we can maybe think again of introducing 2.? But I really wouldn't like to modify anything related to supervision DNs just to make them 'easier' to use by operators, they should IMO continue being as descriptive as possible.

**Comment by q3k** [comment]
We ended up with 2/3 in the form of concise logging, where we have an algorithm for shortening log lines' DN part: https://github.com/monogon-dev/monogon/commit/367ee27b50654bc37358d9172aed7c3d19a32dac .

We still have long supervision tree names, but we can't really work around that.
