### ISSUE TITLE
EFI Unified Kernel Image support (building)

### ISSUE THREAD

**Issue by q3k** [monogon-dev/monogon#78]
We want to wrap a pre-built Linux kernel EFI stub into what the systemd people call 'EFI Unified Kernel Images'.

We're doing this to be able to combine a pre-built Metropolis kernel with an initramfs, or customized Kernel flags and other metadata.

This is, in turn, required to actually have an installer for Metropolis - to both have a customizable installer but also booting the Metropolis kernel.

**Comment by q3k** [comment]
@lorenz is working on implementing an EFI image toolchain to build EFI images.

@msgctl is working on documenting the why in a design doc about the installer.

**Comment by lorenz** [comment]
This is done as of 2f9f387
