### ISSUE TITLE
Get our own OID namespace

### ISSUE THREAD

**Issue by lorenz** [monogon-dev/monogon#82]
This is important for doing custom things with certificates like embedding authorization data and node parameters.

The form for applying is [here](https://pen.iana.org/pen/PenApplication.page), it's free but can take up to 30 days.

@leoluk Do you want to take this?

**Comment by leoluk** [comment]
![image](https://user-images.githubusercontent.com/859697/136961126-e3214cd5-c29b-4476-9a46-c3fac4f1e09a.png)

**Comment by leoluk** [comment]
Your Private Enterprise Number is: **58023** :slightly_smiling_face:
