### ISSUE TITLE
JDK necessary in builder image?

### ISSUE THREAD

**Issue by curiousleo** [monogon-dev/monogon#83]
Seeing "Installing adwaita-cursor-theme-3.36.1-1.fc32.noarch" scroll past as `create_container.sh` was running, I looked into where that dependency came from. It's `java-11-openjdk`:

https://github.com/monogon-dev/monogon/blob/6ef7f9bb94890748cc7c635f187fce7c5f497fe3/build/ci/Dockerfile#L34

I then removed this package from `build/ci/Dockerfile` and re-ran `create_container.sh`, `scripts/bin/bazel clean && scripts/bin/bazel test //...` and tried the IntelliJ plugin, and everything appeared to continue to work as expected.

My recommendation would be:
- If the included JDK is indeed unnecessary, it can be removed -- no need to include it and its dependencies in the builder image!
- If the JDK is necessary, it seems likely that `java-11-openjdk-headless` would suffice. This would avoid a few themes, fonts and Xorg dependencies from being pulled in, which are almost certainly unused.

**Comment by leoluk** [comment]
Thanks for the report - you're right, we probably don't need it since Bazel brings its own JRE anyway.

Want to submit a Gerrit CL to remove it?

**Comment by curiousleo** [comment]
> Want to submit a Gerrit CL to remove it?

Sure, I'll give that a go!

**Comment by curiousleo** [comment]
I've never used Gerrit before. There seems to be an authentication error. Here's what I've done so far.

# `commit-msg` hook: works

I set up the Gerrit `commit-msg` hook as follows:
```bash
f="$(git rev-parse --git-dir)/hooks/commit-msg" && \
  mkdir -p "$(dirname "$f")" && \
  curl -Lo "$f" https://review.monogon.dev/tools/hooks/commit-msg && \
  chmod +x "$f"
```

This hook works -- I can see that a line with "Change-Id: [...]" was added to my commit message.

# `git push`: fails

I'm following [the walkthrough](https://review.monogon.dev/Documentation/intro-gerrit-walkthrough.html#_creating_the_review), which says:

```console
$ git commit
[master 3cc9e62] Change to a proper, yeast based pizza dough.
 1 file changed, 10 insertions(+), 5 deletions(-)

$ git push origin HEAD:refs/for/master
[... pushes successfully ...]
```

`origin` in the example refers to the Gerrit server, not GitHub. So I set up the Gerrit remote as follows:

```console
$ git remote add gerrit https://review.monogon.dev/monogon

$ git fetch gerrit
[... successful ...]

$ git remote show gerrit
* remote gerrit
  Fetch URL: https://review.monogon.dev/monogon
  Push  URL: https://review.monogon.dev/monogon
  HEAD branch: main
  Remote branch:
    main new (next fetch will store in remotes/gerrit)
  Local ref configured for 'git push':
    main pushes to main (fast-forwardable)
```

But then when I try to push, there's an authentication step:

```console
$ git push gerrit HEAD:refs/for/master
Username for 'https://review.monogon.dev': [waits for input]
```

So it looks like I need an account on the Gerrit instance. Is that correct?

**Comment by leoluk** [comment]
Easiest way is to log into Gerrit with a Google account, add your SSH key there and use Git over SSH to push.

**Comment by leoluk** [comment]
Here's a tutorial for Wormhole, which also applies here (except it's a different Gerrit instance): https://github.com/certusone/wormhole/blob/dev.v2/CONTRIBUTING.md#quickstart

**Comment by curiousleo** [comment]
Thanks for the pointers! Here's the Gerrit review link: https://review.monogon.dev/c/monogon/+/413

**Comment by curiousleo** [comment]
Fixed in https://review.monogon.dev/c/monogon/+/413 / https://github.com/monogon-dev/monogon/commit/070ec4eb5f6853185209494455a9a7b751cf32e1.

**Comment by leoluk** [comment]
Actually I think the Jenkins agent may need it 😅

**Comment by curiousleo** [comment]
> Actually I think the Jenkins agent may need it sweat_smile

Oops! That may be a new personal record in "minimal number of contributions before the first build breakage".

> I'll take a stab at testing the CI part to see if the JRE/headless JDK is good enough.

Sounds good to me. If that's too much hassle, please go ahead and revert my commit if that's the quickest way to fix CI!

**Comment by leoluk** [comment]
https://review.monogon.dev/c/monogon/+/414 should fix it for good

**Comment by curiousleo** [comment]
To bring this issue to a close: yes, the JDK is necessary for the Jenkins agent, but the GUI / Xorg dependencies are probably not required, so `headless` will probably do.
