### ISSUE TITLE
Bump versions before MVP release

### ISSUE THREAD

**Issue by q3k** [monogon-dev/monogon#84]
What we should bump:

- [X]  Go (to 1.17),
- [X] gVisor (to a recent release)
- [x] Linux (to newest release within LTS, or new LTS)
- [x] Kubernetes (to 1.22/1.23)
- [x] Fedora Container (to 35)

We we should consider:
- [x] Other Go dependencies?

**Comment by leoluk** [comment]
Did we already figure out how to do our own Bazel builds now that upstream killed it?

If not, perhaps we should stay with a LTS release that still has it for the MVP?

**Comment by q3k** [comment]
@leoluk I'll burn that bridge when I get to it.

In the meantime, @lorenz bumped Bazel to 4.2 (latest), Go to 1.17.1 (latest), gVisor to release-20211101.0.

**Comment by lorenz** [comment]
I bumped Linux to 5.15.2 (latest, scheduled for LTS)

**Comment by msgctl** [comment]
@lorenz says "fietsje has been acting up with GVisor". We should spend some time on that before moving on with other Go deps.

**Comment by q3k** [comment]
Still in progress by @lorenz, (nearly) everything's building, with a purely gomod-resolved source tree (no more Fietsje).

A lot of large Kubernetes patches got dropped (eg. providerless/dockerless prod binaries as that's now supported by upstream). A lot of small patches still have to be updated.

While Kubernetes commits most generated files to Git, they don't commit OpenAPI generated files... for now, at least. We'll still have to tie the generation of that into our build system.

The main issue is that it's a large change that will touch over 150 files, mostly BUILDfiles. But we'll deal with this.

**Comment by lorenz** [comment]
Bumped all Go dependencies (K8s 1.23.4, runc 1.1.0, containerd 1.6.1, coredns 1.9.1, gRPC 1.45.0, gVisor latest) and Linux to the newest point release (5.15.32). Should be good enough for this issue. We still need automation to help us with our rather large dependency zoo.
