### ISSUE TITLE
Supervisor TestPanic flake

### ISSUE THREAD

**Issue by lorenz** [monogon-dev/monogon#86]
Observed on https://jenkins.monogon.dev/job/gerrit-presubmit-monogon/job/44%252F444%252F1/1/console

```
--- FAIL: TestPanic (0.05s)
    supervisor_test.go:372: runnable 'one' didn't acknowledge cancel
FAIL
```

**Comment by leoluk** [comment]
That's new.... perhaps related to the Go (or library) updates?

**Comment by q3k** [comment]
I've seen this recently, too. I wanna say it started appearing after https://github.com/monogon-dev/monogon/commit/ba7bf7dc83c15cbd94a1f71b7992df7d7fc7d752 , but that would mean there's a race somewhere for such a small change to trigger this (which is possible, the supervisor tests aren't great in this regard IIRC).

I can look into it once I'm done with some other stuff this week.

**Comment by q3k** [comment]
Actually, let's deflake this now.

**Comment by q3k** [comment]
```
$ scripts/bin/bazel test //metropolis/pkg/supervisor:go_default_test --runs_per_test=100
[...]
//metropolis/pkg/supervisor:go_default_test                              FAILED in 4 out of 100 in 13.1s
```
Yeah, 4% flaky, not geat. Let's investigate.

**Comment by q3k** [comment]
Just moved everything to block instead. We lose nice test errors, but we also make them sound. There's unfortunately no way to reliably implement this sort of 'would block' check when trying to see if another goroutine is in some given state, we just have to block.

https://review.monogon.dev/c/monogon/+/445

This should fix it.

**Comment by q3k** [comment]
Resolved.
