### ISSUE TITLE
Integrate with godoc / pkg.go.dev / `go get`?

### ISSUE THREAD

**Issue by q3k** [monogon-dev/monogon#87]
We should have godocs somewhere.

Ideally, we would just be accessible over pkg.go.dev as any other library. This however requires integrating at least somewhat with `go get` / mod compatible repositories.

If that's too complex (or too complex for now), we should maybe at least generate and host our own godocs...

**Comment by fionera** [comment]
Support for `go get` was added. https://pkg.go.dev/source.monogon.dev
