### ISSUE TITLE
Do not run Debug Service on non-dbg builds

### ISSUE THREAD

**Issue by q3k** [monogon-dev/monogon#91]
Currently `bazel run //:launch` starts a Metropolis instance with the debug service wide open - we shouldn't do that, everything should be managed via the Curator and metroctl.

This likely depends on the tail of functionality to be ported to the Management API:

- [x] https://github.com/monogon-dev/monogon/issues/90
- [x] https://github.com/monogon-dev/monogon/issues/113 (for later)
- [ ] *Optional: Supervisor introspection*

**Comment by msgctl** [comment]
Currently blocked on #90.

**Comment by lorenz** [comment]
https://review.monogon.dev/c/monogon/+/552 handles disabling the service. Log access will be migrated in a follow-up to that one.

**Comment by q3k** [comment]
Log access followup: https://github.com/monogon-dev/monogon/issues/113
