### ISSUE TITLE
Installer Generator (metroctl install genusb) is slow

### ISSUE THREAD

**Issue by q3k** [monogon-dev/monogon#92]
Because of some shenanigants with go-diskfs we're generating the installer image annoyingly slowly (one physical block at a time).

We should fix this and make it fast. At least temporarily we should let the user know that things are happening: a progress bar, or even a log entry noting that the subsequent operation is slow.

**Comment by q3k** [comment]
(whether we fix go-diskfs, fork go-disk-fs or write something totally independent is a decision left to the implementor)

**Comment by lorenz** [comment]
Fixed in ad131883747f73e51526dd6f163df23b913f69ed
