### ISSUE TITLE
Shipping Firmware, Microcode and other blobs

### ISSUE THREAD

**Issue by q3k** [monogon-dev/monogon#93]
We will need network/storage firmware for some platforms sooner or later.

We should also almost definitely ship Intel Microcode (and other CPU vendor?) updates.

Both of these fall under a generic umbrella of 'shipping blobs', be it from linux-firmware or elsewhere. One important thing to investigate is whatever licensing issues might arise from this, perhaps look into how some Linux Distribution Vendors do it.

**Comment by q3k** [comment]
Another consideration: do we need to ship blobs before we have root storage? If so, where do we store them? We have no initrd in Metropolis, only in the installer.

And: how do we pick which firmware to ship? linux(-firmware?) supposedly has tooling to pick firmware based on the kernel config, that might make it easier. `/lib/firmware` on Fedore is 280MB, we probably don't want to just ship everything always unless we have a very good reason to do so.

**Comment by q3k** [comment]
Related discussion: do we want to let users load arbitrary firmware? Probably not:

1. If we ship a set of firmware that is needed for our drivers, there should be no need to load anything, unless we hit things that are not redistributable
2. The attack surface gets uncomfortably large when we allow for this, so even if we do, we can't rely on this for any sealed / high assurance policies.
3. If we allow arbitrary firmware uploads, the user has another way to 'brick' a broken installation by uploading a broken firmware that prevents the installation from working.

So, so far it looks like we prefer to be responsible for shipping a working set of firmware as part of Metropolis and simplify things in the big picture, rather than rely on users being able to inject their own firmware.

**Comment by q3k** [comment]
Relevant Linux API: https://www.kernel.org/doc/html/latest/driver-api/firmware/index.html

**Comment by q3k** [comment]
fwprune has landed (tool to prune firmware blobs based on kernel config)

We still need:
 - a rule to run fwprune
 - ... or integrate fwprune into erofs_image (maybe after renaming it to something less generic)

@lorenz or myself will get to it, as it requires integration with somewhat hairy rules that also touch somewhat hairy bazel structures (tree artifacts)

**Comment by lorenz** [comment]
Another idea: erofs_image / node_image take a metropolis.node.build.mkerofs.fsspec.FSSpec which gets merged into the normally-generated one. Then the fwprune rule just outputs this spec and doesn't actually copy anything. @q3k Thoughts?

**Comment by q3k** [comment]
@lorenz is currently working on the above buildsystem integration.

https://review.monogon.dev/c/monogon/+/521

**Comment by lorenz** [comment]
Firmware is handled by https://review.monogon.dev/c/monogon/+/534, only microcode is left.

**Comment by q3k** [comment]
Microcode pending review:

https://review.monogon.dev/c/monogon/+/546

https://review.monogon.dev/c/monogon/+/549
