### ISSUE TITLE
Allow split logging within a single runnable (ie., "consensus" and "etcd" should be distinguishable)

### ISSUE THREAD

**Issue by leoluk** [monogon-dev/monogon#95]
See title - I've found myself confused reading the logs until I realized that this was etcd log output, not our own code. 

Should we just call it by its name and name it "etcd"?

**Comment by q3k** [comment]
The reason it's called consensus is to actually separate the wrapping service/runnable (consensus) from the etcd daemon itself. The proble is more that we're logging both these codebases into the same supervisor-provided logging target, making it difficult to pick apart each one.

I wanted to actually fix it by making etcd log into a sub-element of the logtree, but I haven't gotten around to doing that yet.

I'll then extend this issue to implement the possibility of logging into 'fake' runnables, or somehow else decoupling logging targets from the supervision subtree.

Tangentially related to #85 .

**Comment by q3k** [comment]
Fix for etcd/consensus logging: https://review.monogon.dev/c/monogon/+/1356
