### ISSUE TITLE
Node Join Flow

### ISSUE THREAD

**Issue by q3k** [monogon-dev/monogon#99]
Nodes which previously Registered into a cluster should be able to Join it again on reboot.

- [ ] #105

**Comment by q3k** [comment]
Split out the join credentials part into #105.

**Comment by msgctl** [comment]
[WIP] https://review.monogon.dev/c/monogon/+/537

**Comment by q3k** [comment]
Current progress: making bootstrapping nodes also generate/save join keys and other node data. The unclear separation between node/core/cluster and node/core/roleserver strikes again.

**Comment by lorenz** [comment]
@msgctl posted a new revision on friday, needs a test to restart also the bootstrapping node.

**Comment by q3k** [comment]
Split up into smaller chunks:

https://review.monogon.dev/c/monogon/+/667
https://review.monogon.dev/c/monogon/+/556
https://review.monogon.dev/c/monogon/+/664

Being reviewed by me.

**Comment by lorenz** [comment]
Has been merged, the first node still can't restart until #112 is fixed.
